# http://travis-ci.org/Crompulence/cpl-library

os: linux
sudo: required

language: python
python:
    - 2.7

env:
    - MPI=mpich3 GCC_VERSION=5
#    - MPI=openmpi GCC_VERSION=5

branches:
  only:
    - master

cache:
  apt: true

before_install:

    - sh ./make/travis/travis-install-gcc.sh 'gcc-'$GCC_VERSION;
    - sh ./make/travis/travis-install-fortran.sh 'gfortran-'$GCC_VERSION
    - test -n $CC  && unset CC
    - test -n $CXX && unset CXX
    - export MPI_BUILD_DIR=$TRAVIS_BUILD_DIR/mpi
    - export MPI_DIR=$MPI_BUILD_DIR/$MPI
    - sh ./make/travis/travis-install-mpi.sh $MPI $MPI_BUILD_DIR
    - sh ./make/travis/travis-install-mpi4py.sh $MPI_DIR

install:
    - export PATH=$MPI_DIR/bin:$PATH
    - make PLATFORM=gcc BUILD=debug

before_script:
    - export PATH=$MPI_DIR/bin:$PATH
    - export CPL_PATH=`pwd`
    - source $CPL_PATH/SOURCEME.sh
    - sudo apt-get -qq update
    - sudo apt-get install -qq valgrind


script:
    - make test-all
#    - make test-examples
#    - make webdocs-all
    - make test-valgrind
    - make test-gtests
    - make test_Dragmodels


after_success:
     - echo "Build Success"

#after_failure:
#    - which mpif90
#    - locate mpif90
#    - echo $MPI_BUILD_DIR $CXX $MPI_DIR
#    - cat $MPI_BUILD_DIR/config.log



notifications:
  email: true
