# http://travis-ci.org/Crompulence/cpl-library
# Note bug report #5221 required apt-get update for gfortran
#    - MPI=mpich3 CPP=gcc-5 fortran=gfortran
#    - MPI=mpich2 CPP=gcc-5 fortran=gfortran
#    - MPI=openmpi CPP=gcc-5 fortran=gfortran
#    sh ./make/travis/travis-install-fortran.sh $fortran &&
#    - if [ ${fortran} != "gfortran" ];
#    then 
#        sh ./make/travis/travis-install-gcc.sh $GCC_VERSION; 
#    else 
#        sh ./make/travis/travis-install-fortran.sh $fortran &&
#        sh ./make/travis/travis-install-gcc.sh $GCC_VERSION;
#    fi

os: linux
sudo: required
language: python
python:
    - 2.7

env:
    - MPI=mpich3 GCC_VERSION=5 fortran=gfortran

branches:
  only:
    - master

cache:
  apt: true

before_install:

    #If not gfortran then we'll need to get elsewhere 
    #- if [ ${fortran} != "gfortran" ];
    #  then sh ./make/travis/travis-install-fortran.sh $fortran;
    #  else echo "Getting gfortran from c++ repo";
    #  fi
    - sh ./make/travis/travis-install-gcc.sh 'gcc-'$GCC_VERSION;
    - sh ./make/travis/travis-install-fortran.sh $fortran
    - test -n $CC  && unset CC
    - test -n $CXX && unset CXX
    - alias gcc='gcc-'$GCC_VERSION
    - alias cc='gcc-'$GCC_VERSION
    - alias g++='g++-'$GCC_VERSION
    - alias c++='c++-'$GCC_VERSION
    - alias gfortran='gfortran-'$GCC_VERSION
    - which gfortran
    - export MPI_BUILD_DIR=$TRAVIS_BUILD_DIR/mpi
    - sh ./make/travis/travis-install-mpi.sh $MPI $MPI_BUILD_DIR
    - export MPI_DIR=$MPI_BUILD_DIR/$MPI

install:
    - echo "looking for MPI in "$MPI_DIR 
    - export PATH=$MPI_DIR/bin:$PATH
    - cd ./cpl
    - make

before_script:
    - export PATH=$MPI_DIR/bin:$PATH
    - cd ../demo
    - make
    - MPIEXEC='mpiexec'

script:
    - cd ./run
    - echo "test"
#    - $MPIEXEC -n 8 ./md/mdProgram : -n 4 ./cfd/cfdProgram -v -f --no-builddir --exclude=spawn

after_failure:
    - which mpif90
    - locate mpif90
    - echo $MPI_BUILD_DIR $CXX $MPI_DIR
    - cat $MPI_BUILD_DIR/config.log



notifications:
  email: false
