
# http://travis-ci.org/Crompulence/cpl-library
os: linux
sudo: required
language: python
python:
    - 2.7

# set up build matrix
matrix:
  include:

    #Build for 14.04
    - dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6 gcc-6 libstdc++-6-dev gfortran-6
      # change default compiler to newer gcc-6
      env:
        - GCC_VERSION=6
        - CXX_COMPILER=g++-6
        - C_COMPILER=gcc-6
        - F_COMPILER=gfortran-6
        - MPI=mpich3
        - platform=gcc

    #Build for 16.04
    - dist: xenial
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7 gcc-7 libstdc++-7-dev gfortran-7
      env:
        - GCC_VERSION=7
        - CXX_COMPILER=g++-7
        - C_COMPILER=gcc-7
        - F_COMPILER=gfortran-7
        - MPI=mpich3
        - platform=gcc

    #Build for 16.04 with openMPI
    #- dist: xenial
    #  compiler: gcc
    #  addons:
    #    apt:
    #      sources:
    #        - ubuntu-toolchain-r-test
    #      packages:
    #        - g++-7 gcc-7 libstdc++-7-dev gfortran-7
    #  env:
    #    - GCC_VERSION=7
    #    - CXX_COMPILER=g++
    #    - C_COMPILER=gcc
    #    - F_COMPILER=gfortran
    #    - MPI=openmpi
    #    - platform=openmpi_gcc

branches:
  only:
    - master

 
cache:
  directories:
    - mpi


before_install:
    - test -n $CC  && unset CC
    - test -n $CXX && unset CXX
    - export MPI_BUILD_DIR=$TRAVIS_BUILD_DIR/mpi
    - export MPI_DIR=$MPI_BUILD_DIR/$MPI
    - sh ./make/travis/travis-install-mpi.sh $MPI $MPI_BUILD_DIR $GCC_VERSION
    - sh ./make/travis/travis-install-mpi4py.sh $MPI_DIR

install:
    - export PATH=$MPI_DIR/bin:$PATH
    - make PLATFORM=$platform BUILD=debug

before_script:
    - export PATH=$MPI_DIR/bin:$PATH
    - export CPL_PATH=`pwd`
    - source $CPL_PATH/SOURCEME.sh
    - sudo apt-get -qq update
    - sudo apt-get install -qq valgrind

script:
    - make test-pytest-initialisation
    - make test-examples
    - make test-valgrind
    - travis_wait 30 make test-pytest-mapping
    - make test-gtests
    - make test_Dragmodels
#    - make test-granular
#    - make webdocs-all


after_success:
     - echo "Build Success"

#after_failure:
#    - which mpif90
#    - locate mpif90
#    - echo $MPI_BUILD_DIR $CXX $MPI_DIR
#    - cat $MPI_BUILD_DIR/config.log



notifications:
  email: true
