# http://travis-ci.org/Crompulence/cpl-library
# Note bug report #5221 required apt-get update for gfortran
#    - MPI=mpich2 CPP=gcc-5 fortran=gfortran
#    - MPI=openmpi CPP=gcc-5 fortran=gfortran

os: linux
sudo: required
language: python
python:
    - 2.7

env:
    - MPI=mpich3 CPP=gcc-5 fortran=gfortran

branches:
  only:
    - master

cache:
  apt: true

before_install:
    - sh ./make/travis/travis-install-fortran.sh $fortran
    - sh ./make/travis/travis-install-gcc.sh $CPP
    - test -n $CC  && unset CC
    - test -n $CXX && unset CXX
    - sh ./make/travis/travis-install-mpi.sh $MPI

install:
    - cd ./cpl
    - make

before_script:
    - cd ../demo
    - make
    - MPIEXEC='mpiexec'
    - cd ./run

script:
    - echo "test"
#    - $MPIEXEC -n 8 ./md/mdProgram : -n 4 ./cfd/cfdProgram -v -f --no-builddir --exclude=spawn

notifications:
  email: false
